# Generated by Django 3.1.1 on 2020-09-24 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
