# Generated by Django 2.1 on 2018-08-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
