# Generated by Django 2.1 on 2018-08-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180827_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.Instructor'),
        ),
    ]
