# Generated by Django 2.1 on 2018-08-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.Building'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Ders bitiş saati'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Ders başlangıç saati'),
        ),
    ]
