# Generated by Django 2.2.4 on 2019-08-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190805_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
    ]
