# Generated by Django 2.1 on 2018-08-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20180827_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='schedule.Section'),
            preserve_default=False,
        ),
    ]
