# Generated by Django 2.2.4 on 2019-08-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20190829_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['code']},
        ),
    ]
