# Generated by Django 2.2.4 on 2019-09-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20190829_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('code',)},
        ),
    ]
